FROM mcr.microsoft.com/devcontainers/typescript-node:24

RUN apt update && apt upgrade -y && apt install -y direnv && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

COPY direnv.toml /home/node/.config/direnv/
COPY .bashrc /home/node/
